# Generated by Django 5.0.6 on 2026-08-16 15:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category_type', models.CharField(choices=[('canteen', 'Canteen'), ('stationery', 'Stationery'), ('hostel_supply', 'Hostel Supply'), ('book', 'Book')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold_out', 'Sold Out'), ('sold', 'Sold')], db_index=True, default='active', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CanteenDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='canteen_detail', serialize=False, to='listings.listing')),
                ('is_veg', models.BooleanField(default=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelSupplyDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hostel_supply_detail', serialize=False, to='listings.listing')),
                ('request_only', models.BooleanField(default=True)),
                ('supply_category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationeryDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stationery_detail', serialize=False, to='listings.listing')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('unit', models.CharField(max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book_detail', serialize=False, to='listings.listing')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('worn', 'Worn')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='canteendetail',
            constraint=models.CheckConstraint(check=models.Q(('prep_time_minutes__isnull', True), ('prep_time_minutes__gte', 1), _connector='OR'), name='canteen_prep_time_positive'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['vendor'], name='listings_li_vendor__851bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category_type', 'status'], name='listings_li_categor_41309c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='listings_li_status_29a9da_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='listing_price_non_negative'),
        ),
    ]
