# Generated by Django 5.0.6 on 2026-08-31 17:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('required_by_date', models.DateField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('warden_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_warden', models.ForeignKey(blank=True, limit_choices_to={'role': 'warden'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hostel_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(limit_choices_to={'category_type': 'hostel_supply'}, on_delete=django.db.models.deletion.PROTECT, related_name='hostel_requests', to='listings.listing')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HostelRequestStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='hostel_requests.hostelrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hostelrequest',
            index=models.Index(fields=['student', 'status'], name='hostel_requ_student_9f16b1_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelrequest',
            index=models.Index(fields=['assigned_warden', 'status'], name='hostel_requ_assigne_874073_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelrequest',
            index=models.Index(fields=['status', '-created_at'], name='hostel_requ_status_e94c7e_idx'),
        ),
    ]
